# Generated by Django 4.1.6 on 2023-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': '"weather"."daily_weather"',
            },
        ),
        migrations.CreateModel(
            name='YearlyWeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=16)),
                ('year', models.IntegerField()),
                ('avg_min_temp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_max_temp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_precipitation', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': '"weather"."yearly_weather_stats"',
            },
        ),
    ]
